### ISSUE TITLE
[FEATURES REQUEST] VOLUME indicator

### ISSUE THREAD

**Issue by bvebve** [taniman/profit-trailer-enhancements#752] opened 2020-12-01 19:44 UTC
Need to catch when the volume is over the media average, probably using one indicator for actual volume and a second indicator for SMA(volume).

Maybe indicator settings like this:

> VOLUME_candle_period
> VOLUME_lenght     // for SMA(VOLUME)      default=0
> VOLUME_offset       // default=0

**Comment by taniman** [comment] 2021-01-26 20:08
a new indicator in 2.5.0 will return volume. Part to of this request is a duplicate of another

**Closed by taniman** 2021-01-26 20:08 UTC
