### ISSUE TITLE
Reversal Trading Strategy - New Method to deal with BAGS

### ISSUE THREAD

**Issue by juato4** [taniman/profit-trailer-enhancements#264] opened 2018-04-25 01:15 UTC
Reversal trading (RT) is a technique to keep on trading profitably when prices move downwards after an asset has been purchased.

The principle is to use the already invested amount of base currency to accumulate more units of the quote currency while prices are moving downwards. When prices eventually rise again, the -then bigger- bag can be sold for profit at a lower price point than without reversal trading.

Trading fees paid while in reversal trading are all accounted for.

![38331646-13c489aa-3854-11e8-95b4-8b9143edf69b](https://user-images.githubusercontent.com/35824627/39187370-81eda00c-47a3-11e8-8c6e-80860c33fd22.PNG)

Reversal trading starts when the current price is a set percentage lower than the average bought price (or last bought price, when using RT together with DU), this is defined with RT_SELL_BUYDOWN. The initial bag gets sold for base currency (RT_SELL) and the invested amount is reserved for buying back more units when prices drop further. When the price then drops by a percentage defined with RT_BUY_BUYDOWN, quote currency gets bought (RT_BUY). You now own more quote currency than you initially bought, at a lower price per unit.

This process will repeat when prices keep dropping, enabling you to keep accumulating quote currency without investing additional assets.

When prices rise again, your normal trading strategy will sell the assets for profit.

In case prices recover before RT_BUY_BUYDOWN is reached, the initial bag will be bought back to continue normal trading (RT_BUYBACK).

Optionally, the AIRDROP feature allows you to cash out accumulated quote assets in base currency. This takes place when the difference between the initial bag and the current bag size is bigger than MIN_VOLUME_TO_SELL. Reversal trading then continues with the initial amount of quote currency bought.

Warnings:

Do not activate reversal trading on existing bags that are already down a lot! The decision to run reversal trading or not should best be made before you start trading a pair, this way the process can kick in timely.
Reversal trading math is done based on your trading history, if your last sell order was at loss (and not caused by stop limit), reversal trading would immediately start when you enable it. To prevent unwanted reversal trading, make sure to either have a profitable last sell order or to have set IGNORE_TRADES_BEFORE at a time after your last sell order at loss. Alternatively, you can set a maximum price difference between current price and average bought price with RT_MAXBAG_PROTECTION, to prevent RT from starting on pairs that already lost a lot of value.
When a buyback occurs during reveral trading, slightly more base currency gets invested.

![38986278-43c97dc6-43cc-11e8-9313-a6bbaeb68be6](https://user-images.githubusercontent.com/35824627/39187400-964dcee6-47a3-11e8-8306-b63b1cb1de24.jpg)

Parameter | Default value | Description
-- | -- | --
RT_ENABLED | false | Values: true or false. When set to true and prices drop, reversal trading will try to use the assets originally invested in your bag to accumulate a bigger bag, which can be sold for profit earlier than the original bag. When double up is enabled, RT will start when DU_CAP_COUNT is reached.
RT_SELL_BUYDOWN | 1 | Values: numerical - represents a percentage. Defines the percentage drop after initial buy or RT_BUY to trigger RT_SELL. Make sure to set this higher then the spread between bid and ask to prevent unwanted buybacks.
RT_BUY_BUYDOWN | 2 | Values: numerical - represents a percentage. This defines the percentage the price has to drop after RT_SELL to trigger RT_BUY.
AIRDROP | false | Values: true or false. Set this to true to enable airdrop and automatically cash out accumulated quote currency during reversal trading. The initial bag size will be kept, surplus bigger than MIN_VOLUME_TO_SELLwill be airdropped.
RT_MAXBAG_PROTECTION | 10 | Values: numerical - represents a percentage. Sets the maximum difference between the average bought price and current price for starting RT. When the difference is bigger, RT won't start. This is used as a protection against starting reversal trading on bags that already dropped too much for the process to work effectively.
IGNORE_TRADES_BEFORE | 0 | Values: unix timestamp in milliseconds (in GMT)Optional parameter to force reversal trading to ignore trades before a set time. Use https://currentmillis.com/to convert human readable time in GMT to unix timestamps in milliseconds.

**Comment by clownfish44** [comment] 2018-04-25 22:59
This is literally the definition of DCA in not so many words. Please just use DCA it works!

**Comment by juato4** [comment] 2018-04-25 23:01
No, you are not understanding the feature… please let the people vote… dont close at your criterion

**Comment by keithofaptos** [comment] 2018-04-25 23:11
Scaling out of each position.and of each coin pair sounds useful.especially for larger balance traders.

**Comment by juato4** [comment] 2018-04-25 23:15
Thanks @SgtBatten

**Comment by juato4** [comment] 2018-04-25 23:16
@clownfish44 need to reed and learn a little more.

**Comment by SgtBatten** [comment] 2018-04-25 23:49
do not change it again or i will close it, every request here is a feature request

**Comment by juato4** [comment] 2018-04-25 23:51
And these not?:
https://github.com/taniman/profit-trailer-enhancements/issues/263
https://github.com/taniman/profit-trailer-enhancements/issues/260
https://github.com/taniman/profit-trailer-enhancements/issues/257
https://github.com/taniman/profit-trailer-enhancements/issues/255
https://github.com/taniman/profit-trailer-enhancements/issues/226
https://github.com/taniman/profit-trailer-enhancements/issues/147

**Comment by juato4** [comment] 2018-04-26 19:52
@clownfish44 "We are not going to steal a strategy or create a strategy to lose money to hope to buy lower and make money" 

… please google Reversal Trading… you really do not know what is being talked about in this post… do you know about Scalping Strategy?….. you need to reed a lot.

**Comment by stevenshizzleh** [comment] 2018-05-04 21:33
This is thought-provoking. I know people are familiar with the concept of DCA, but this seems to be a more technical and deliberate approach. 

A simple question here as I play devil's advocate: Can we accomplish the same goal by having a large quantity of shallow DCAs with very low buy percentages? E.g., levels 1-20 with 1% costs? Could that effectively do the same thing?

Either way -- this is worth looking into.

**Comment by angelsomar** [comment] 2018-05-05 02:18
It seems to me a good method even to optimize the performance of pairs in holdingIt seems to me a good method even to optimize the performance of pairs in holding

**Comment by js8749** [comment] 2018-05-05 06:33
This would be awesome for the keep_balance or keep_balance_percentage to automatic trade USDT(BTC or ETH) and grow our balance when market fluctuate.

**Comment by juato4** [comment] 2018-05-20 21:16
What one of the developers of Reversal Trading says about why PT is not implementing Reversal Trading on PT: 

<img width="575" alt="captura de pantalla 2018-05-20 a la s 18 15 57" src="https://user-images.githubusercontent.com/35824627/40283763-f23f9a16-5c59-11e8-95b3-01ca12067bbf.png">

**Comment by CryptosWORLD** [comment] 2018-05-21 01:56
i agree is good to see this strategy to PT
check this youtuber talks about DCA and Reversal trading (talks about Gunbot and Profit Trailer)
and explains the diiff of each strategy ...
https://www.youtube.com/watch?v=HjjnbdtyDak&feature=youtu.be&t=12m42s
the info i share about the subject starts about 12m 42 sec ..

**Comment by juato4** [comment] 2018-05-21 02:05
Just thinking with a pair like BTC-ETH or BTC-USDT …. is really good

**Comment by jadiesel** [comment] 2018-06-12 22:12
Step 2 here is a simple Stop-Loss.
Step 3 is simply buying a new position - which the bot will do if it is a good buy.

I fail to see the usefulness of making this a dedicated strategy: You sold at a loss and hoped to buy again in the future for a profit.   

I could be missing something, but This is exactly how things work when I run a stop-loss strategy.

![image](https://user-images.githubusercontent.com/20715803/41319935-3558520a-6e63-11e8-8973-1a5a7651cea2.png)

**Comment by juato4** [comment] 2018-06-12 22:33
@jadiesel is more than that… please see the video.

**Comment by CryptosWORLD** [comment] 2018-06-12 22:53
here is an update in how it works https://github.com/GuntharDeNiro/Gunthy/wiki/Reversal-trading
i copy some part from the link .. more info in the link ..
" ...

How it works

Reversal trading starts when the current price is a set percentage lower than the last bought price, this is defined with RT_GAIN. The initial bag gets sold for base currency (RT_SELL) and the invested amount is reserved for buying back more units when prices drop further. When the price then drops by a percentage defined with RT_BUY_LEVEL, quote currency gets bought (RT_BUY). You now own more quote currency than you initially bought, at a lower price per unit.

This process will repeat when prices keep dropping, enabling you to keep accumulating quote currency without investing additional assets. Required funds are locked for the pair in reversal trading, and can't be used by other pairs.

With TM_RT_SELL, or when using bb as selling strategy, it's possible to place an RT_SELL at a higher rate than the previous RT_BUY, enabling you to reach a profitable exit point much faster.

When prices reach an overall profitable price (EXIT POINT), a normal sell order is placed.

In case prices recover to the break even point before an RT_BUY could be made, the initial bag will be bought back to continue normal trading (RT_BUYBACK).

The exact process for reversal trading is dependant on the strategies used for buying on selling. There are slight differences described in detail below.

    Warnings:

        Do not activate reversal trading on existing bags that are already down a lot unless you use TM_RT_SELL! The decision to run reversal trading or not should best be made before you start trading a pair, this way the process can kick in timely.
        Reversal trading math is done based on your trading history, if your last sell order was at loss (and not caused by stop limit), reversal trading would immediately start when you enable it. To prevent unwanted reversal trading, make sure to either have a profitable last sell order or to have set IGNORE_TRADES_BEFORE at a time after your last sell order at loss. Alternatively, you can set a maximum price difference between current price and average bought price with RT_MAXBAG_PROTECTION, to prevent RT from starting on pairs that already lost a lot of value.
... "

**Comment by CryptosWORLD** [comment] 2018-06-12 23:07
--> with a STOP LOSS we have a % of loss that means that our buy strategy on specific pair on specific time fail. And we free balance for future new buy opportunities of any pair BUT WE HAVE A LOSS.

--> with reversal strategy as i can understand.. the bot sell on a loss (you give when to sell) yes but to free balance to reenter in the current pair in a better possition and rebuys (like dca) better positions until (the initial loss goes to zero, fees calculated also and) there is a profit. take the loss and make it to a profit.. its different than stop loss.

**Comment by CryptosWORLD** [comment] 2019-06-03 07:15
i also have see implementations of this strategy in other bots haasbot, crypto hopper , wolfpack bot
as i understand 
if a strategy is not configured correct in a specific pair, in a specific time period, in specific trend may give you a BAG
THIS STRATEGY helps to sell this bag and rebuy it in cheaper price and sell it wit ha profit. But if the trend is still in bear will not work ... the best is this strategy starts when the specific pair is in bull trend ... so at my opinion we need indicators (= gibes bull singal trend looking multiple time periods) that will give the signal to this strategy when start

**Comment by cryptocoyns** [comment] 2019-06-20 01:32
This is an ill conceived method that is trying to compensate for poor risk management. In psychological terms this was studied back in the 70's and is known as Prospect Theory. They found that people prefer to take on additional risk rather than admit they were wrong in the first place. This usually resulted in these people getting further in trouble. The need to always be right outweighed their better judgement. This method is selling for a loss and re-buying the same coin lower in hopes of the coin returning to profit. However there is no guarantee the coin wont just keep falling. Just look at Bitcoin at the end of last year, a lot of people said it wouldn't go lower than $6000 and it did, dropping to around $3000. This is the downfall of these sort of methods. Losses are a part of trading you have to be able to accept that or if you cannot then stop trading. Risk management and Money management are the key to better trading results. You are better off just taking the loss early and get on with your trading. Also look into your position sizing if you are having sizeable losses. This is also misnamed it is not Reversal Trading. In trading terms Reversal trading universally refers to Trend Reversal trading where you are trading the bullish or bearish trend reversal patterns.

**Comment by taniman** [comment] 2020-05-14 03:46
Simplified version implemented some time ago

**Closed by taniman** 2020-05-14 03:46 UTC
