### ISSUE TITLE
[Feature Request] DCA Coins in the order they entered DCA

### ISSUE THREAD

**Issue by wolfman77** [taniman/profit-trailer-enhancements#828] opened 2021-04-19 09:13 UTC
Hi,

having an option that allows the first coin that enters DCA and has a "bought time" or level reached, gets DCAed until the end FIRST.

Currently they jump into and out of DCA, until you have several with one or more levels of DCA applied, until you run out of money. This is capital intensive and take much more in the end (as you need to start managing the bot additionally).

Ideas for approach:
FIFO (first in first out)
LILO (last in last out)
HIFO (highest in first out - the one with least minus percentage)
LIFO (lowest in first out - the one with highest minus percentage)

I´d rather vote for FIFO, but these are options I can think of. It would mean less management of the bot if you have e.g. 7 coins in the reds, and it starts with the first that entered DCA and keeps buying (and ONLY THAT COIN) until its sold.

**Comment by taniman** [comment] 2021-04-24 17:39
We already have BUY Priority logic in the bot and DCA max pairs. So this seems like duplicate of existing functions.

**Closed by taniman** 2021-04-24 17:39 UTC
